import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style= "Regular" }
size = 13
offset = { y = 1 }

[env]
TERM = "xterm-256color"
