"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_red)\
$os\
$username\
[](fg:color_red bg:color_orange)\
$hostname\
[](fg:color_orange bg:color_yellow)\
$directory\
[](bg:color_aqua fg:color_yellow)\
$git_branch\
[](bg:color_blue fg:color_aqua)\
$rust\
$dotnet\
$nodejs\
$php\
[](fg:color_blue bg:color_background_dark)\
[](fg:color_background_dark bg:color_background_darker)\
$time\
$character"""

palette = 'gruvbox_dark'

add_newline = true

[palettes.gruvbox_dark]
color_text_light = '#fbf1c7'
color_background_dark = '#665c54'
color_background_darker = '#3c3836'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_text_light bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_text_light bg:color_aqua)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_background_darker"
format = '[[  $time ](fg:color_text_light bg:color_background_darker)]($style)'

[os]
disabled = false
style = "fg:color_text_light bg:color_red"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:color_text_light bg:color_red"
style_root = "fg:color_text_light bg:color_red"
format = '[ $user ]($style)'

[hostname]
ssh_only = false
disabled = false
style = "fg:color_text_light bg:color_orange"
format = "[ $ssh_symbol$hostname ]($style)"

[directory]
style = "fg:color_text_light bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[dotnet]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) \($tfm\)](fg:color_text_light bg:color_blue)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text_light bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text_light bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text_light bg:color_blue)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_background_darker bg:color_green)[](bold fg:color_green)'
error_symbol = '[](bold fg:color_background_darker bg:color_red)[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_background_darker bg:color_green)[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_background_darker bg:color_purple)[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_background_darker bg:color_purple)[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_background_darker bg:color_yellow)[](bold fg:color_yellow)'
